# Generated by Django 5.1.1 on 2024-10-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_categoria_slug_tipo_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='slag',
            new_name='slug',
        ),
    ]
